language: csharp

before_script:
  - chmod a+x ./travis-build.sh
  - chmod a+x ./run-tests.sh
  - chmod a+x ./after-success.sh
script:
  - ./travis-build.sh
  - ./run-tests.sh
after_success:
  - ./after-success.sh
