/*
 * Assignment 2
 *
 * An API for assignment 2
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BookApi.Models.Entities
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class Review
    {
        /// <summary>
        /// Gets or Sets ReviewID
        /// </summary>
        [DataMember(Name="reviewID")]
        public int ReviewID { get; set; }
        /// <summary>
        /// Gets or Sets BookId
        /// </summary>
        [DataMember(Name="book_id")]
        public int BookId { get; set; }
        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name="user_id")]
        public int UserId { get; set; }
        /// <summary>
        /// Gets or Sets Stars
        /// </summary>
        [DataMember(Name="stars")]
        public int Stars { get; set; }
        /// <summary>
        /// Gets or Sets UserReview
        /// </summary>
        [DataMember(Name="userReview")]
        public string UserReview { get; set; }

    }
}
